#!/sbin/ash

mknod /dev/console c 5 1
mknod /dev/null    c 1 3
mknod /dev/ptmx    c 4 2
mknod /dev/ram0    b 1 0
mknod /dev/tty0    c 5 0
mknod /dev/ttyS0   c 4 64

mount /dev/pts
mount /proc
mount /sys

PATH=/sbin

export NCPUS=`grep processor /proc/cpuinfo | wc -l`

echo Number of CPUs: $NCPUS | /sbin/qsim_out

cd data

/sbin/mark_app

/sbin/qsim_in | tar -x
if [ $? != 0 ]; then
  echo Untar input failed. Are you providing a .tar archive? | /sbin/qsim_out
fi

if [ -ne runme.sh ]; then
  echo \"runme.sh\" not found. Input .tar must contain this. | /sbin/qsim_out
fi

/sbin/chmod +x ./runme.sh
/sbin/ash ./runme.sh 2>&1 | /sbin/qsim_out

# Spin forever.
while true; do
  echo --- error: init still alive after program exit ---
  sleep 10
done
