#!/sbin/ash

mknod /dev/console c 5 1
mknod /dev/null    c 1 3
mknod /dev/ptmx    c 4 2
mknod /dev/ram0    b 1 0
mknod /dev/tty0    c 5 0
mknod /dev/ttyS0   c 4 64

mount /dev/pts
mount /proc
mount /sys

PATH=/sbin

export NCPUS=`grep processor /proc/cpuinfo | wc -l`

echo Number of CPUs: $NCPUS | /sbin/qsim_out

cd data

echo We have booted a 64-bit machine. | /sbin/qsim_out

#/sbin/mark_app

#/sbin/qsim_in > extractme.tar
#tar -xvf extractme.tar
#/sbin/chmod +x ./runme.sh
#./runme.sh 2>&1 | /sbin/qsim_out

# Spin forever.
while true; do
  echo --- error: init still alive after program exit ---
  sleep 10
done
